# This is where the nutrinomics report is generated

# Imports
from docx.shared import Pt, Cm
from WordDocument import WordEditing as wd
import ELT

class NutrinomicsReport(wd):
    def __init__(self, sample_id, dataframe):
        super().__init__(sample_id, dataframe)
        self.nutri_markers = ELT.Extract().nutrimarkers()

    def nutrinomics_IA(self):

        nutrinomics_genes = [
            "ABCB1",
            "ACE",
            "ADIPOQ",
            "ADRA2A",
            "ALDH2",
            "BCO1",
            "BDNF-AS;BDNF",
            "DRD2",
            "FTO",
            "GC",
            "GCK,YKT6",
            "IGF1",
            "LDLR",
            "LOC105447645;FUT2",
            "MAO-B",
            "MC4R",
            "MTNR1B",
            "NADSYN1",
            "NBPF3",
            "Sult1A1",
            "Sult1E1",
            "TCF7L2",
            "TMEM165;CLOCK",
            "TNFa",
            "UCP2",
            "VDR"
        ]
        nutri_markers = self.nutri_markers[self.nutri_markers['gene_name'].isin(nutrinomics_genes)]

        df = self.dataframe[self.dataframe['sample_id'] == self.sample_id]
        df = df[df['gene'].isin(nutrinomics_genes)]
        df.drop(['sample_id','phenotype'], axis='columns', inplace=True)
        df.rename(columns={'gene': 'Gen', 'genotype': 'Uitslag'}, inplace=True)

        dbSNP_list = []
        for gen in nutrinomics_genes:
            index = nutri_markers[nutri_markers['gene_name'] == gen].index.values
            dbSNP_list.append(nutri_markers.loc[index, 'dbSNP_RS_ID'].item())

        df.insert(1, 'dbSNP', dbSNP_list)
        return df

    def logo_titel_header(self):
        self.document.add_picture("Input/Icons/niFGo_logo.png")
        self.heading("\nFarmacogenetisch Rapport")
        self.heading("Bijlage nutrigenomics {}".format(self.sample_id))
        self.colour_bar()
        self.heading("De uitslag nutrigenomics:",lined=True)

    def table(self, style = "Table Grid"):
        """
        Creates a Word table from a dataframe
        :param: style: The style of the table, default is Table Grid.
        :return: A Word table in the specified document
        """

        df = self.nutrinomics_IA()

        # add a table to the end and create a reference variable
        # extra row is so we can add the header row
        t = self.document.add_table(df.shape[0] + 1, df.shape[1])
        t.style = style

        # add the header rows.
        for j in range(df.shape[-1]):
            header_cells = t.rows[0].cells
            paragraph = header_cells[j].paragraphs[0]
            run = paragraph.add_run(df.columns[j])
            run.bold = True
            run.font.name = 'Calibri'
            run.font.size = Pt(12)

        # add the rest of the data frame
        for i in range(df.shape[0]):
            for j in range(df.shape[-1]):
                normal_cells = t.rows[i+1].cells
                paragraph = normal_cells[j].paragraphs[0]
                run = paragraph.add_run(str(df.values[i, j]))
                run.font.name = 'Calibri'
                run.font.size = Pt(12)

        t.allow_autofit = False
        width_dict = {0:5.49, 1:3.75 ,2:1.59} #{0:4, 1:3.5 ,2:2 ,3:10} when frequencies are included
        for i in range(len(width_dict)):
            for cell in t.columns[i].cells:
                cell.width = Cm(width_dict[i])

    def Toelichting(self):
        self.document.add_page_break()
        self.heading("Toelichting\n", lined=True)

        def first_word_bold(text,chosen_font='Calibri', chosen_size=11):
            split_text = text.split(sep=" ", maxsplit=1)
            bold_word = split_text[0]
            rest = split_text[1]
            paragraph = self.document.add_paragraph()
            self.linepacing(paragraph,spacing=1)
            run = paragraph.add_run("{} ".format(bold_word))
            run.bold = True
            run.font.name = chosen_font
            run.font.size = Pt(chosen_size)
            run = paragraph.add_run(rest)
            run.bold = False    #Niet nodig om dit te declareren, maar wel fijn voor de leesbaarheid
            run.font.name = chosen_font
            run.font.size = Pt(chosen_size)

        first_word_bold("ABCB1 codeert voor een membraaneiwit, dat betrokken is bij de transportfunctie van cellen. Dit eiwit, P-glycoproteïne, fungeert als een pomp, die bepaalde stoffen uit de cel kan pompen, voordat ze zich kunnen ophopen in het lichaam en schade kunnen veroorzaken. ABCB1 is dus ook betrokken bij de manier, waarop ons lichaam medicijnen opneemt, verdeelt, afbreekt en uitscheidt. Dit betekent dat variaties in ABCB1 invloed kunnen hebben op hoe gevoelig we zijn voor bepaalde medicijnen. Dit geldt onder andere voor antidepressiva, antistollingsmedicijnen, maagbeschermers, antibiotica, anti-epileptica en cholesterolverlagers. In sommige gevallen kunnen variaties in ABCB1 zelfs leiden tot resistentie tegen medicijnen, wat betekent, dat de medicijnen dan niet goed werken."
                        "\nHet ABCB1 gen speelt ook een belangrijke rol in de regulering van de bloed-hersenbarrière. Deze barrière controleert, welke stoffen vanuit de bloedbaan de hersenen kunnen bereiken. Variaties in ABCB1 kunnen dus invloed hebben op de werking van deze barrière en zo bijdragen aan de ontwikkeling van bepaalde neurologische aandoeningen.Het ABCB1 gen speelt ook een belangrijke rol in de regulering van de bloed-hersenbarrière. Deze barrière controleert, welke stoffen vanuit de bloedbaan de hersenen kunnen bereiken. Variaties in ABCB1 kunnen dus invloed hebben op de werking van deze barrière en zo bijdragen aan de ontwikkeling van bepaalde neurologische aandoeningen."
                        "\nIn dit onderzoek is de variatie rs1045642 getest. T geeft de aanwezigheid van de variatie aan. De meest voorkomende testuitslag bij mensen van West-Europese afkomst is C/T. De variatie rs1045642 is geassocieerd met een lagere expressie van P-glycoproteïne. Dit betekent dat mensen met de testuitslag C/T en T/T een lagere P-glycoproteïne activiteit hebben dan mensen met de testuitslag C/C."
                        "\nDit kan het effect hebben, dat medicijnen, die door P-glycoproteïne worden getransporteerd, minder goed uit het lichaam worden verwijderd. Hierdoor kunnen medicijnen hogere plasmaconcentraties bereiken. Dat kan weer leiden tot een toegenomen toxiciteit of een verminderde werking. Dit kan het effect hebben, dat medicijnen, die door P-glycoproteïne worden getransporteerd, minder goed uit het lichaam worden verwijderd. Hierdoor kunnen medicijnen hogere plasmaconcentraties bereiken. Dat kan weer leiden tot een toegenomen toxiciteit of een verminderde werking."
                        "\nVan verschillende medicijnen is bekend, dat ze worden beïnvloed door de variatie rs1045642. Deze medicijnen zijn:")
        self.bulletpoint("Digoxin: wordt gebruikt bij de behandeling van hartfalen. De variatie rs1045642 is geassocieerd met een lagere plasmaconcentratie van Digoxin bij mensen met de testuitslag T. Dit kan leiden tot verminderde werking van het medicijn.",size=11)
        self.bulletpoint("Dabigatran: wordt gebruikt bij de behandeling van trombose. De variatie rs1045642 is geassocieerd met een hogere plasmaconcentratie van Dabigatran bij mensen met de testuitslag T. Dit kan leiden tot een verhoogd risico op bloedingen.",size=11)
        self.bulletpoint("Amlodipine: wordt gebruikt bij de behandeling van hoge bloeddruk. De variatie rs1045642 is geassocieerd met een hogere plasmaconcentratie van Amlodipine bij mensen met de testuitslag T. Dit kan leiden tot een toename van de bijwerkingen, zoals duizeligheid en slaperigheid.",size=11)
        self.bulletpoint("Cannabis: de variatie rs1045642 is geassocieerd met een hogere plasmaconcentratie van Cannabis bij mensen met de testuitslag T, met het risico op verslaving bij gebruik van cannabis.",size=11)
        run = self.document.add_paragraph().add_run("Belangrijk is ook dat, ook omgevingsfactoren, co-medicatie en voeding van invloed zijn op de activiteit van dit ABCB1. Van Sint-Janskruid is bekend dat gebruik ervan de functie van ABCB1 stimuleert.")
        self.styled_run(run)
        self.document.add_page_break()
        first_word_bold("ACE codeert voor het angiotensine-converterend enzym (ACE), een enzym dat angiotensine I omzet in angiotensine II. Angiotensine II is een hormoon, dat vernauwing van de bloedvaten veroorzaakt. ACE is ook van invloed op het evenwicht van vocht en zout in ons lichaam. Variaties in ACE kunnen invloed hebben op hoeveel van het ACE-enzym ons lichaam produceert, hoe actief het is en hoe dit bijdraagt aan de manier, waarop ons lichaam de bloeddruk reguleert."
                        "\nHet ACE-enzym heeft twee functies: namelijk ten eerste bevordert het de afgifte van een hormoon genaamd aldosteron, dat de balans van natrium en kalium in de nieren reguleert. Dit kan leiden tot een verhoging van de bloeddruk. Ten tweede breekt het enzym bradykinine af, een stof die de bloedvaten verwijdt en de bloeddruk kan verlagen."
                        "\nIn dit onderzoek is de variatie rs4341 getest. D geeft de aanwezigheid van de variatie aan. Deze aanduiding heeft te maken met de typeringen Insertion (I) en Deletion (D), die invloed hebben op de productie van het ACE-enzym. Mensen kunnen het II-, ID- of DD-genotype hebben. Het DD-genotype wordt geassocieerd met een lagere ACE-enzymactiviteit."
                        "\nHet I/D-polymorfisme in ACE is onderzocht in verband met verschillende gezondheidsrisico’s als hoge bloeddruk en cardiovasculaire aandoeningen. Verschillende onderzoeken hebben aangetoond dat mensen met het I/I genotype een hoger risico hebben op het ontwikkelen van hoge bloeddruk. Bij mensen met het D/D genotype is dit risico afwezig."
                        "\nBij weergeven van de uitslag wordt voor Insertion “G” en voor Deletion “C” gebruikt."
                        "\nMet andere woorden, de genetische variaties in ACE kunnen invloed hebben op hoe gevoelig iemand is voor het ontwikkelen van hoge bloeddruk. Studies hebben aangetoond dat, mensen met de testuitslag D, een hogere bloeddruk hebben en een hoger risico hebben op het ontwikkelen van diabetes type 2 en nierfalen, dan mensen met de testuitslag I.")
        first_word_bold("ADIPOQ codeert voor het adiponectine-enzym, dat voornamelijk wordt geproduceerd door vetweefsel. Dit enzym speelt een cruciale rol bij het reguleren van hoe ons lichaam omgaat met suiker en vet. Het adiponectine enzym is van invloed op insulinegevoeligheid. "
                        "\nAdiponectine verbetert de gevoeligheid van onze cellen voor insuline, een hormoon dat helpt bij het reguleren van de bloedsuikerspiegel. Dit betekent dat het ervoor zorgt dat onze cellen beter reageren op insuline, waardoor ze glucose (suiker) effectiever uit het bloed kunnen opnemen. Dit helpt bij het handhaven van gezonde bloedsuikerspiegels en vermindert het risico op insulineresistentie en type 2-diabetes. Een lage adiponectine concentratie wordt geassocieerd met een verminderde insulinegevoeligheid. Logischerwijs worden hoge concentraties adiponectine geassocieerd met een goede insulinegevoeligheid."
                        "\nDaarnaast stimuleert adiponectine de verbranding van vetzuren in onze spierweefsels, wat bijdraagt aan een gezond vetmetabolisme en kan helpen bij het voorkomen van obesitas en diabetes type 2."
                        "\nAdiponectine speelt een rol bij de regulering van de eetlust en het verzadigingsgevoel, wat van invloed kan zijn op het lichaamsgewicht en de voedselopname. Bovendien heeft adiponectine invloed op onze eetlust en ons verzadigingsgevoel, wat kan bijdragen aan het reguleren van ons lichaamsgewicht en onze voedselinname."
                        "\nAdiponectine heeft ook ontstekingsremmende eigenschappen, wat betekent dat het helpt om ontstekingsreacties in ons lichaam te verminderen. Dit is bijzonder belangrijk voor het voorkomen van hart- en vaatziekten, omdat het helpt bij het verminderen van de ophoping van plaque in onze slagaders, wat kan leiden tot atherosclerose (verharding en vernauwing van de slagaders)."
                        "\nIn dit onderzoek is de variatie rs17300539 getest. A geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een lagere expressie van adiponectine. Een lagere expressie verhoogt het risico op insulineresistentie. Dat kan leiden tot problemen met de bloedsuikerspiegel. De testuitslag G/G is het meest voorkomend (86%) onder de West-Europese bevolking. Studies hebben aangetoond dat mensen met de testuitslag A/G en A/A een hoger risico hebben op het ontwikkelen van diabetes type 2 en hart- en vaatziekten dan mensen met de testuitslag G/G.")
        self.document.add_page_break()
        first_word_bold("ADRA2A codeert voor de α2A-adrenerge receptor. Deze receptor is betrokken bij de regulering van hoe ons zenuwstelsel reageert op stress. Deze receptor komt voor in verschillende weefsels en organen, waaronder de hersenen, het hart en de bloedvaten. De α2A-adrenerge receptor bindt zich aan de neurotransmitter noradrenaline. In de hart en de bloedvaten kan activering van de receptor leiden tot vernauwing van de bloedvaten en verhoging van de bloeddruk."
                        "\nIn de hersenen reguleert de α2A-adrenerge receptor de afgifte van neurotransmitters, zoals noradrenaline en dopamine. Dit heeft invloed op onze stemming, aandacht en cognitieve functies."
                        "\nDe α2A-adrenerge receptor is ook aanwezig op de bètacellen van de alvleesklier, waar insuline wordt geproduceerd. De activering van deze receptor kan de afgifte van insuline beïnvloeden en daarmee de regulering van de bloedsuikerspiegel."
                        "\nBovendien speelt de α2A-adrenerge receptor een rol bij onze fysiologische reactie op stress. Het kan bijdragen aan de regulering van de 'vecht-of-vluchtreactie', die ons lichaam mobiliseert om te reageren op stressvolle situaties."
                        "\nGenetische variaties in ADRA2A kunnen van invloed zijn op de functie en activiteit van de α2A-adrenerge receptor en worden in een aantal gevallen geassocieerd met het risico op te hoge bloeddruk, angststoornissen, depressie en ADHD."
                        "\nIn dit onderzoek is de variatie rs10885122 getest. T geeft de aanwezigheid van de variatie aan. De testuitslag G/G is het meest voorkomend onder de West-Europese bevolking. De testuitslag G/T en T/T worden geassocieerd met het risico op een hoge bloedsuikerspiegel, wat relevant kan zijn voor het ontwikkelen van Type 2-diabetes.")
        first_word_bold("ALDH2 codeert voor het enzym aldehydedehydrogenase 2. Dit enzym speelt een belangrijke rol bij de afbraak van ethanol, de alcohol die we drinken. Dit enzym is vooral actief in de lever en helpt bij het omzetten van acetaldehyde, een schadelijke stof die ontstaat bij de afbraak van alcohol, in acetaat, een minder toxische verbinding. Het ALDH2-enzym is verantwoordelijk voor de tweede stap in de afbraak van alcohol. Nadat alcohol is omgezet in acetaldehyde, zorgt ALDH2 ervoor dat acetaldehyde verder wordt omgezet in acetaat, dat het lichaam veilig kan afvoeren."
                        "\nDe omzetting van acetaldehyde in acetaat is cruciaal omdat acetaldehyde giftig is en schade kan veroorzaken aan verschillende weefsels in het lichaam, vooral aan de lever. Bij mensen met een goed functionerend ALDH2-enzym (testuitslag G/G) verloopt dit metabolische proces efficiënter, wat bijdraagt aan een snellere en effectievere verwijdering van acetaldehyde."
                        "\nVariaties in het ALDH2-gen kunnen leiden tot verminderde of afwezige activiteit van het enzym, wat kan leiden tot alcoholintolerantie. Bij mensen met een testuitslag A/A of A/G hoopt acetaldehyde zich snel op in het lichaam, nadat ze alcohol hebben gedronken. Dit kan symptomen veroorzaken zoals roodheid in het gezicht (de bekende \"alcohol flush reactie\"), misselijkheid, braken, hartkloppingen en hoofdpijn. (https://www.youtube.com/watch?v=sD9tZtP9_ng)"
                        "\nALDH2 speelt een sleutelrol bij de bescherming tegen oxidatieve stress en ontstekingsreacties."
                        "\nIn dit onderzoek is de variatie rs671 getest. A geeft de aanwezigheid van de variatie aan. De testuitslag G/G is het meest voorkomend onder de West-Europese bevolking. De testuitslag A/G en A/A geven een verminderde werking van het ALDH2-enzym aan en kunnen dus van invloed zijn op hoe goed iemand alcohol kan verwerken en tolereren in vergelijking met de testuitslag G/G.")
        self.document.add_page_break()
        first_word_bold("BCO1 codeert voor het enzym bètacaroteen-15,15’-monooxygenase-eiwit. Dit enzym speelt een belangrijke rol bij de omzetting van bètacaroteen in vitamine A. Bètacaroteen is een carotenoïde pigment dat wordt aangetroffen in veel groenten en fruit, zoals wortels, zoete aardappelen, pompoenen en spinazie. Het is eigenlijk een voorloper van vitamine A. Het BCO1-enzym versnelt het proces waarbij bètacaroteen wordt omgezet in vitamine A (ook wel retinol genoemd). Dit helpt ervoor te zorgen dat de niveaus van vitamine A in ons lichaam binnen een gezond bereik blijven, zodat we geen tekorten of overdosering van vitamine A krijgen."
                        "\nVitamine A is belangrijk voor onze gezondheid, vooral voor onze ogen en ons immuunsysteem. Bètacaroteen, dat wordt aangetroffen in voedingsmiddelen, draagt ook bij aan onze algemene afweer tegen schadelijke stoffen in ons lichaam, omdat het fungeert als een antioxidant."
                        "\nIn dit onderzoek is de variatie rs7501331 getest. T geeft de aanwezigheid van de variatie aan De testuitslagen C/T en T/T geven een mogelijk verhoogd risico op een vitamine A tekort aan. Een ernstig vitamine A tekort kan de oorzaak zijn van problemen met de ogen (nachtblindheid) en een verminderde immuunrespons, wat betekent dat het lichaam minder goed in staat is om infecties te bestrijden. Mensen met de testuitslag C/T en T/T kunnen minder goed vetten afbreken dan mensen met een testuitslag C/C. Het is belangrijk op te merken dat voeding ook een rol speelt in het bepalen van iemands vitamine A-status. Bij aangetoonde aanwezigheid van deze variatie kan een darmmicrobioom onderzoek worden overwogen.")
        first_word_bold("BDNF-AS codeert voor de brain-derived neurotrophic factor (BDNF). BDNF speelt een cruciale rol in de hersenen en het zenuwstelsel en is betrokken bij verschillende belangrijke processen. Het is essentieel voor een goede werking van de hersenen en wordt geassocieerd met zaken zoals neuroplasticiteit (de hersenen die zich aanpassen), leerprocessen en geheugen."
                        "\nVariaties in BDNF, inclusief de mogelijke rol van BDNF-AS, kunnen invloed hebben op de niveaus van BDNF in de hersenen. Dit kan leiden tot problemen met de hersenfunctie en wordt geassocieerd met neurologische en neuropsychiatrische aandoeningen. ( https://www.natuurdietisten.nl/voeding-en-kruiden-voor-je-bdnf-brein/)"
                        "\nIn dit onderzoek is de variatie rs6265 getest. Deze variatie wordt aangegeven als het Val66Met-polymorfisme. Deze variatie leidt tot een verandering in het BDNF-eiwit op positie 66, waarbij het aminozuur valine (Val) wordt vervangen door methionine (Met). De testuitslag Met is de variatie. Onderzoek heeft aangetoond dat het Val66Met-polymorfisme de afgifte van BDNF kan beïnvloeden. Mensen met het Met66-allel kunnen lagere niveaus van BDNF in de hersenen hebben dan mensen met het Val66-allel. Het Met66-allel wordt in verband gebracht met de kans gevoeliger te zijn voor psychiatrische aandoeningen, zoals depressie, angststoornissen, schizofrenie en de ziekte van Alzheimer. Mensen met het Val66-allel hebben over het algemeen een lager risico op deze aandoeningen."
                        "\nBij weergeven van de uitslag wordt voor Val “C” en voor Met “T” gebruikt."
                        "\nDe testuitslag Val/Met wordt geassocieerd met een licht risico op ADHD en depressies. De testuitslag Met/Met wordt geassocieerd met een grotere gevoeligheid voor depressies en moeite hebben met deelname aan verkeersactiviteiten.")
        self.document.add_page_break()
        first_word_bold("DRD2 codeert voor de dopamine D2-receptor. Deze receptor is gevoelig voor de neurotransmitter dopamine, een chemische boodschapper, die een grote rol speelt in de werking van ons zenuwstelsel. De dopamine D2-receptor is een essentieel onderdeel van het dopamine-systeem in onze hersenen en speelt een sleutelrol bij het reguleren van verschillende neurologische processen, onder andere beloning, stemming, motivatie en bewegingscontrole."
                        "\nDe D2-receptor heeft een centrale rol als het gaat om beloningsgedrag. Veranderingen in hoe deze receptor werkt, kunnen invloed hebben op hoe mensen beloningen ervaren en hoe ze reageren op dingen die plezier of voldoening geven."
                        "\nHet DRD2-gen en de D2-receptor zijn betrokken bij verschillende psychiatrische aandoeningen, waaronder schizofrenie, verslavingsstoornissen en ADHD. Variaties in DRD2 zijn geassocieerd met een verhoogd risico op deze aandoeningen."
                        "\nDe dopamine D2-receptor is ook betrokken bij motorische functies en kan van invloed zijn op de controle over bewegingen. Veranderingen in de activiteit van deze receptor kunnen leiden tot motorische stoornissen."
                        "\nOok heeft de D2-receptor invloed op hoe ons lichaam pijn waarneemt en hoe het reageert op pijn. Het speelt een rol bij het reguleren van onze pijnperceptie en -reactie."
                        "\nIn dit onderzoek is de variatie rs1076560 getest. A geeft de aanwezigheid van de variatie aan. De testuitslag C/C is de meest voorkomende onder de West-Europese bevolking. De testuitslag A/C wordt geassocieerd met een verhoogd risico op alcoholisme. De testuitslag A/A wordt geassocieerd met een verminderd werkgeheugen. Deze genetische variatie kan dus van invloed zijn op verschillende aspecten van ons gedrag en onze hersenfunctie.")
        first_word_bold("FTO (Fat mass and obesity-associated gene) speelt een belangrijke rol bij het reguleren van ons energiemetabolisme en heeft invloed op de controle van onze voedselinname en ons lichaamsgewicht. FTO lijkt een rol te spelen bij het beïnvloeden van ons lichaamsgewicht en kan het risico op obesitas verhogen. Dit komt deels doordat FTO betrokken is bij het reguleren van onze eetlust en voedselinname. FTO heeft ook invloed op de stofwisseling door onder meer de regulering van de opslag van vetten. Het mechanisme achter deze associaties lijkt te maken te hebben met de regulering van eetlust en energiebalans."
                        "\nNaast obesitas wordt FTO ook in verband gebracht met andere gezondheidsproblemen, waaronder het risico op het ontwikkelen van type 2-diabetes en hart- en vaatziekten."
                        "\nIn dit onderzoek is de variatie rs1121980 getest. A geeft de aanwezigheid van de variatie aan. Dit betekent dat mensen met de variatie A een hogere hoeveelheid FTO in hun lichaam hebben dan mensen met de variatie G. De testuitslag A/G is de meest voorkomende testuitslag (54%) onder de West-Europese bevolking en wordt geassocieerd met een licht risico op overgewicht. De testuitslag A/A wordt geassocieerd met een hoger risico op aanleg tot overgewicht in vergelijking met de testuitslag G/G. Met andere woorden, deze genetische variatie kan van invloed zijn op hoe ons lichaam met gewicht en metabolisme omgaat en het kan ons vatbaarder maken voor overgewicht als we de A/A-testuitslag hebben. Bij aangetoonde aanwezigheid van deze variatie kan een darmmicrobioom onderzoek worden overwogen.")
        self.document.add_page_break()
        first_word_bold("GC codeert voor het vitamine D-bindende enzym Gc-globuline (VDBP). Dit enzym speelt een belangrijke rol in het transport van vitamine D in ons lichaam. Dit enzym is essentieel voor het zorgen dat vitamine D effectief kan worden vervoerd in onze bloedbaan en beschikbaar is voor verschillende lichaamsweefsels."
                        "\nGc-globuline helpt vitamine D vanuit onze bloedsomloop te transporteren naar verschillende organen en weefsels, waar het nodig is voor verschillende lichaamsfuncties. Dit gebeurt ofwel als we vitamine D uit ons voedsel halen of als ons lichaam vitamine D produceert, wanneer we worden blootgesteld aan zonlicht. Gc-globuline heeft ook invloed op hoe ons lichaam vitamine D omzet in zijn actieve vorm, calcitriol. Calcitriol speelt een belangrijke rol in het reguleren van calcium- en fosfaatniveaus en het metabolisme van ons botweefsel."
                        "\nGc-globuline heeft daarnaast effect op ons immuunsysteem en kan ontstekingsreacties reguleren. Het kan ook andere moleculen en enzymen in onze bloedbaan binden en transporteren, waaronder actine, een eiwit dat betrokken is bij de spiercontractie."
                        "\nIn dit onderzoek is de variatie rs2282679 getest. G geeft de aanwezigheid van de variatie aan. Dit betekent dat mensen met de variatie G een minder efficiënte opname van vitamine D hebben dan mensen met de variatie T. De testuitslag T/T is de meest voorkomende testuitslag onder de West-Europese bevolking. De testuitslagen T/G en G/G worden geassocieerd met een verlaagd vitamine D niveau. Een verlaagd vitamine D niveau geeft meer kans op het ontwikkelen van osteoporose en auto-immuun-ziekte en geeft meer risico op botbreuken dan mensen met de testuitslag T. Met andere woorden, deze genetische variatie kan invloed hebben op hoeveel vitamine D er in je lichaam circuleert, wat belangrijk is voor een gezonde werking van veel lichaamsprocessen. Bij aangetoonde aanwezigheid van deze variatie kan ook een darmmicrobioom onderzoek worden overwogen.")
        first_word_bold("GCK codeert voor het glucokinase-enzym, dat betrokken is bij de regulering van de bloedglucosespiegel. Dit enzym zet glucose om in glucose-6-fosfaat in de lever en in de alvleesklier."
                        "\nGlucokinase vervult verschillende belangrijke functies in ons lichaam. In de lever bevordert het de opname en opslag van glucose als glycogeen, wat een vorm van opgeslagen energie is. In de alvleesklier reguleert het de afgifte van insuline, een hormoon dat de hoeveelheid glucose in ons bloed regelt. In de bètacellen van de alvleesklier zorgt glucokinase ervoor dat insuline wordt afgegeven in reactie op veranderingen in de bloedglucosewaarden. Als het glucosegehalte in ons bloed stijgt, bijvoorbeeld na een maaltijd, stimuleert glucokinase de lever en de alvleesklier om meer glucose op te nemen en te verwerken. Als het glucosegehalte in ons bloed daalt, zorgt glucokinase ervoor dat de lever glucose vrijgeeft om de bloedsuikerspiegel weer te verhogen."
                        "\nGlucokinase is ook aanwezig in sommige delen van de hersenen en speelt een rol in de regulering van de eetlust en de glucosespiegels in de hersenen."
                        "\nIn dit onderzoek is de variatie rs4607517 getest. A geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde activiteit van glucokinase. Dit betekent dat mensen met de testuitslag T minder goed glucose kunnen verwerken dan mensen met de variatie G. De testuitslag G/G is de in West-Europa meest voorkomende testuitslag (67%). De testuitslagen A/G en A/A geven risico op te lage bloedglucosespiegels. Met andere woorden, deze genetische variatie kan invloed hebben op hoe ons lichaam reageert op glucose, wat van belang is voor onze bloedsuikerspiegel. Een verminderde activiteit van glucokinase geeft risico op het ontwikkelen van diabetes type 2, een verminderde glucose-tolerantie en een langdurige hogere bloedsuikerspiegel. Bij aangetoonde aanwezigheid van deze variatie kan aanvullend een darmmicrobioom onderzoek worden overwogen.")
        self.document.add_page_break()
        first_word_bold("FUT 2 codeert voor het enzym fucosyltransferase2. Dit enzym speelt een belangrijke rol in ons lichaam door bepaalde suikermoleculen, voornamelijk fucose, te produceren op het oppervlak van cellen en slijmvliezen. Deze suikermoleculen zijn betrokken bij verschillende biologische processen."
                        "\nFUT2 maakt bepaalde bloedgroepantigenen aan op het oppervlak van rode bloedcellen en slijmvliezen. Mensen met een functioneel FUT2-gen worden \"secretors\" genoemd (FUT2 positief), omdat ze deze bloedgroepantigenen kunnen afscheiden, zoals speeksel, tranen, zweet en slijm. Deze antigenen maken deel uit van het ABO-bloedgroepsysteem, dat we kennen van bloedtransfusies. Mensen die niet-secretors (FUT2 negatief) zijn vanwege variaties in FUT2, hebben mogelijk een verminderd risico op infecties met pathogenen die zich hechten aan de door FUT2 geproduceerde suikers."
                        "\nDe suikermoleculen, die door het FUT2-enzym worden geproduceerd, kunnen fungeren als receptoren voor bepaalde micro-organismen, zoals bepaalde stammen van de bacterie Helicobacter pylori en sommige norovirussen. Hierdoor kunnen deze pathogenen zich aan de slijmvliezen in het maagdarmkanaal hechten en infecties veroorzaken. De suikermoleculen, die door FUT2 worden gegenereerd, spelen ook een rol bij de immuunrespons en ontstekingsprocessen in de darmen en andere slijmvliezen."
                        "\nIn dit onderzoek is de variatie rs492602 getest. A geeft de aanwezigheid van de variatie aan. De variant rs492602 is geassocieerd met een verminderde activiteit van fucosidase-2. Dit betekent dat mensen met de testuitslag A minder goed lactose kunnen afbreken dan mensen met de testuitslag G (lactose-intolerantie). De testuitslag A/G is de meest voorkomende testuitslag onder de West-Europese bevolking. De testuitslag G/G wordt geassocieerd met een hoog B12 niveau bij vrouwen. De testuitslagen A/G en A/A wijzen op een normaal B12 niveau. Met andere woorden, deze genetische variatie kan invloed hebben op of je een \"secretor\" bent of niet, wat op zijn beurt kan samenhangen met je risico op bepaalde infecties. Aangetoond is dat variaties in FUT2 kunnen leiden tot een lagere concentratie darmbacteriën, bifidobacteriën en daardoor risico geven op een grotere vatbaarheid voor de ziekte van Crohn en verhoogde serumconcentratie vitamine B12. Bij aangetoonde aanwezigheid van deze variatie kan aanvullend een darmmicrobioom onderzoek worden overwogen.")
        first_word_bold("IGF-1 codeert voor somatomedine C, een enzym dat betrokken is bij de regulering van de groei en ontwikkeling van het lichaam. IGF-1 is een belangrijke mediator van de groei en vermenigvuldiging van cellen in verschillende delen van ons lichaam, zoals botten, spieren, weefsels en organen. Tijdens de kindertijd en adolescentie is IGF-1 essentieel voor een normale groei en ontwikkeling. Het zorgt ervoor dat onze botten groeien en sterker worden, onze spieren toenemen en onze organen zich ontwikkelen."
                        "\nIGF-1 heeft ook invloed op onze stofwisseling, wat betekent, dat het helpt bij het reguleren van hoe ons lichaam koolhydraten, vetten en eiwitten verwerkt. Dit draagt bij aan het behoud van een evenwichtige energiehuishouding."
                        "\nIGF-1 speelt ook een rol bij spiergroei (hypertrofie) en kan bijdragen aan de toename van spiermassa in reactie op lichamelijke activiteit en training."
                        "\nIGF-1 is ook betrokken bij de groei, ontwikkeling en herstel van botten. Het stimuleert de activiteit van osteoblasten, de cellen, die betrokken zijn bij de vorming van nieuw botweefsel."
                        "\nIGF-1 heeft ook invloed op ons zenuwstelsel, met name in de hersenen en kan daarom van invloed zijn op cognitieve functies."
                        "\nGenetische variaties, zoals rs35767 hebben vaak meerdere effecten, variërend van geen merkbare invloed tot het verhogen of verlagen van de vatbaarheid voor bepaalde aandoeningen. In dit onderzoek is de variatie rs35767 getest. A geeft de aanwezigheid van de variatie aan. De variant rs35767 is geassocieerd met een verminderde expressie van IGF-1. Dit betekent dat mensen met de testuitslag A een lagere hoeveelheid IGF-1 in hun lichaam hebben dan mensen met de testuitslag G."
                        "\nDe testuitslag G/G is in West-Europa de meest voorkomende testuitslag. Met andere woorden, deze genetische variatie kan invloed hebben op hoe IGF-1 in ons lichaam functioneert, maar het exacte effect kan variëren van persoon tot persoon en kan van invloed zijn op verschillende aspecten van groei, ontwikkeling en stofwisseling.")
        self.document.add_page_break()
        first_word_bold("LDLR codeert voor het enzym dat de low-density lipoproteïne-receptor (LDLR) wordt genoemd. Deze receptor helpt bij het beheer van cholesterol, een vetachtige stof die in ons bloed circuleert. De belangrijkste taak van LDLR is om te zorgen, dat ons cholesterolgehalte in balans blijft. Dit is belangrijk, omdat te veel van een bepaald type cholesterol, genaamd \"low-density lipoprotein\" (LDL) cholesterol, schadelijk kan zijn voor onze gezondheid en ons risico op hart- en vaatziekten kan verhogen. Een niet goed werkend LDLR kan de oorzaak zijn dat te veel LDL-cholesterolmoleculen in ons bloed blijven circuleren, wat kan leiden tot een verhoogd risico op hart- en vaatziekten. De variaties rs6511720 en rs57217136 in LDLR zijn functionele variaties. Beide allelen creëren versterker-bindende eiwitplaatsen voor transcriptiefactoren (TF's) en kunnen bijdragen aan een verhoogde LDLR-expressie, wat dus geassocieerd wordt met verlaagde LDL-C-niveaus en een 12% lager cardiovasculair-risico. LDLR- expressie is verhoogd bij degenen die het T-allel dragen."
                        "\nEen goed functionerend LDLR is daarom van groot belang voor het handhaven van een gezond cholesterolniveau en het verminderen van het risico op hartproblemen. Als LDLR niet goed werkt, kan een genetische aandoening, genaamd familiaire hypercholesterolemie, daarvan de oorzaak zijn, met als gevolg zeer hoge niveaus van LDL-cholesterol en een verhoogd risico op hart- en vaatziekten."
                        "In dit onderzoek is de variatie rs6511720 getest. T geeft de aanwezigheid van de variatie aan. De variant rs6511720 is geassocieerd met een verminderde activiteit van LDR voor angiotensine II. Dit betekent dat mensen met de testuitslag T minder gevoelig zijn voor angiotensine II dan mensen met de testuitslag G.")
        first_word_bold("MAO-B staat voor Monoamine Oxidase B, een enzym dat betrokken is bij de afbraak van neurotransmitters in de hersenen, met name dopamine. Dopamine een chemische stof in onze hersenen, die een rol speelt bij stemmingen, bewegen en motivatie. De belangrijkste functie van MAO-B is het afbreken van overtollige dopamine om het niveau van dopamine te reguleren, wat belangrijk is voor een goede werking van ons zenuwstelsel"
                        "\nMAO-B is ook betrokken bij de afbraak van andere monoamine neurotransmitters, zoals fenylethylamine, tyramine, serotonine en noradrenaline. De regulering van deze neurotransmitters draagt bij aan een goede werking van het zenuwstelsel en onze stemmingen."
                        "\nSommige medicijnen (Selegiline en Rasagiline) remmen de activiteit van MAO-B. Dit betekent dat deze medicijnen MAO-B vertragen bij het afbreken van dopamine. Dit kan nuttig zijn bij de behandeling van de ziekte van Parkinson, omdat mensen met deze aandoening vaak een tekort hebben aan dopamine. Door MAO-B af te remmen, kunnen deze medicijnen helpen om het dopaminegehalte in de hersenen te verhogen en de symptomen te verminderen."
                        "\nIn dit onderzoek is de variatie rs1799836 getest. C geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde activiteit van MAO-B. Dit betekent dat mensen met de testuitslag C minder snel dopamine, serotonine en noradrenaline afbreken dan mensen met de testuitslag T."
                        "\nOnderzoeksresultaten naar deze variatie zijn echter niet eenduidig. Sommige studies suggereren dat het C-allel geassocieerd kan worden met een verhoogde MAO-B-activiteit, terwijl het T-allel in verband wordt gebracht met een lagere activiteit. Met andere woorden, sommige mensen hebben van nature meer of minder actieve MAO-B-enzymen in hun hersenen en dit kan invloed hebben op hoe hun hersenen dopamine reguleren. Een studie heeft aangetoond, dat mensen met de variant T een hoger risico hebben op het ontwikkelen van ADHD dan mensen met de variant C."
                        "\nAangezien MAO-B op het X-chromosoom ligt, en mannen er hier maar één van hebben, kan het zijn dat het genotype van dit gen in een enkele letter wordt uitgedrukt.")
        self.document.add_page_break()
        first_word_bold("MC4R codeert voor de melanocortine-receptor 4, die een grote rol speelt in ons eetgedrag en hoe ons lichaam energie verwerkt.  Wanneer melanocortine zich bindt aan de MC4R-receptor, wordt een signaal naar de hersenen gestuurd, dat het gevoel van verzadiging verhoogt en de eetlust vermindert. Dus, MC4R helpt ons om ons verzadigd te voelen na een maaltijd."
                        "\nDaarnaast heeft MC4R invloed op hoe ons lichaam calorieën verbrandt en vet opslaat. Door de activiteit van dit gen kunnen de hersenen de verbranding van calorieën en de opslag van vet reguleren. "
                        "\nVariaties in het MC4R-gen behoren tot de bekendste oorzaken van monogene obesitas, een specifiek type obesitas. Als het MC4R-gen niet goed functioneert vanwege een variatie, kan dit leiden tot een verminderde gevoeligheid van de receptor voor verzadigingssignalen. Dit betekent dat mensen met deze variatie mogelijk meer eten met als gevolg gewichtstoename. Deze erfelijke variatie komt bij circa 1-4% van de bevolking voor."
                        "\nIn dit onderzoek is de variatie rs17782313 getest. C geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde affiniteit van MC4R voor melanocortine-4. Dit betekent dat mensen met de testuitslag G minder gevoelig zijn voor melanocortine-4 dan mensen met de testuitslag T. De testuitslag T/T is de meest voorkomende testuitslag (51%) onder de West-Europese bevolking. De testuitslag C/T ene C/C worden geassocieerd met een hoger BMI (Body Mass Index), wat kan wijzen op een neiging tot overgewicht. Bij aangetoonde aanwezigheid van deze variatie kan aanvullend een darmmicrobioom onderzoek worden overwogen.")
        first_word_bold("MTNR1B codeert voor de melatonine receptor 1B (MT2). Deze receptor speelt een grote rol in twee belangrijke dingen: onze biologische klok en hoe ons lichaam suiker (glucose) verwerkt. Onze biologische klok regelt wanneer we wakker zijn en wanneer we slapen. Melatonine, een stof die in ons lichaam wordt aangemaakt, heeft daar invloed op. MTNR1B heeft invloed op onze gevoeligheid voor melatonine en dat beïnvloedt ons slaap-waakritme en kan daardoor oorzaak zijn voor slaapstoornissen."
                        "\nNaast regulering van het slaap-waakritme is MTNR1B ook betrokken bij ons circadiane ritme, dat is als een soort innerlijke klok, die ons lichaam vertelt wanneer het moet slapen en wakker worden (24 uurs ritme)."
                        "\nOnderzoek heeft aangetoond dat variaties in MTNR1B ook verband houden met hoe ons lichaam suiker verwerkt, vooral glucose. Glucose is de suiker, die ons lichaam gebruikt als energiebron. Als er iets misgaat in de regulering van glucose, kan dat leiden tot diabetes type 2, waarbij de bloedsuikerspiegel te hoog wordt."
                        "\nVariaties in MTNR1B verhogen ook de kans op insulineresistentie, wat betekent dat onze cellen niet goed reageren op insuline (het hormoon dat de bloedsuiker reguleert), wat de bloedsuikerspiegel kan verhogen. In dit onderzoek is de variatie rs10830963 getest. G geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde activiteit van MTNR1B voor melatonine. Dit betekent dat mensen met de testuitslag G minder gevoelig zijn voor melatonine dan mensen met de testuitslag C. De testuitslagen C/G en G/G geven een verhoogd risico op diabetes type 2 en zwangerschapsdiabetes. De testuitslag C/C komt bij 45% van de West-Europese bevolking voor. De testuitslag C/G komt voor bij 51% van de West-Europese bevolking. Dit betekent dat veel mensen deze genetische variatie hebben. Dit kan van invloed zijn op hoe hun lichaam reageert op melatonine en glucose. Daarnaast kan ook aanvullend een darmmicrobioom onderzoek worden overwogen.")
        self.document.add_page_break()
        first_word_bold("NADSYN1 codeert voor het enzym NAD synthetase 1, dat het co-enzym NAD produceert. Het co-enzym NAD is betrokken bij tal van biochemische reacties in de cel, zoals de energieproductie in de mitochondriën. Nad speelt een belangrijke rol in de oxidatieve fosforylering, een proces, waarbij energie wordt geproduceerd in de vorm van adenosinetrifosfaat (ATP). De functie van NADSYN1 is dus gerelateerd aan de productie en regulering van NAD."
                        "\nNAD fungeert ook als een soort helper (cofactor) voor verschillende enzymen, die betrokken zijn bij belangrijke processen in ons lichaam, zoals glycolyse (de afbraak van glucose), de citroenzuurcyclus en oxidatieve stressrespons."
                        "\nVariaties in NADSYN1 kunnen leiden tot een verminderde productie van NAD. Dit kan problemen veroorzaken in de stofwisseling van onze cellen en zelfs bijdragen aan de ontwikkeling van verschillende ziekten, waaronder neurodegeneratieve aandoeningen (Parkinson en Alzheimer)."
                        "\nNADSYN1 heeft ook invloed op het vitamine D niveau. In dit onderzoek is de variatie rs12785878 getest. T geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde productie van NAD+. Dit betekent dat mensen met de testuitslag T een lagere hoeveelheid NAD+ in hun lichaam hebben dan mensen met de testuitslag G. De testuitslagen T/G en T/T worden geassocieerd met vitamine D-insufficiëntie. Vitamine D is belangrijk voor je botten en algehele gezondheid. Ook een aanvullend darmmicrobioom onderzoek kan worden overwogen bij lage vitamine D niveaus.")
        first_word_bold("NBPF3 codeert voor een eiwit, dat een rol speelt in de ontwikkeling van ons zenuwstelsel. Ons zenuwstelsel is het systeem in ons lichaam, dat onze hersenen en zenuwen omvat. NBPF3 zou ook invloed kunnen hebben op hoe goed onze hersenen blijven functioneren, naarmate we ouder worden."
                        "\nNBPF3 wordt ook in verband gebracht met het afvoeren van vitamine B6 uit ons lichaam. Vitamine B6 is noodzakelijk voor een goede werking van ons zenuwstelsel, helpt bij de productie van rode bloedcellen en speelt een rol bij de manier waarop ons lichaam suikers verwerkt. Het juiste functioneren van het zenuwstelsel, rode bloedcellen en ook bij de stofwisseling van suiker. Een laag niveau B6 kan leiden tot bloedarmoede. Symptomen van een laag vitamine B6-niveau zijn vermoeidheid en ontsteking van de tong en mond."
                        "\nIn dit onderzoek is de variatie rs4654748 getest. T geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde expressie van NBPF3. Dit betekent dat mensen met de testuitslag T een lagere hoeveelheid NBPF3 in hun hersenen hebben dan mensen met de testuitslag C. De testuitslag C/C betekent dat je waarschijnlijk een normaal niveau vitamine B6 hebt.  De testtestuitslagen C/T en T/T geven een licht risico op een vitamine B6 tekort. Aanwezigheid van de variatie rs4654748 wordt in de literatuur in verband gebracht met meer kans op het ontwikkelen van ADHD in vergelijking met de testuitslag C.")
        first_word_bold("SULT1A1 codeert voor het enzym sulfotransferase 1A1, dat helpt om schadelijke stoffen te neutraliseren. Dit proces wordt fase II-detoxificatie genoemd en vindt onder andere plaats in de lever. Het enzym zet medicijnen om naar een inactieve vorm en regelt de verwijdering uit ons lichaam. SULT1A1 speelt een sleutelrol bij het bewaken van de hormonale balans in ons lichaam. Een  verminderde activiteit kan de effectiviteit en bijwerkingen van bepaalde medicijnen (paracetamol) beïnvloeden, omdat de sulfatering een belangrijke stap is in het afbreken van medicijnen. Omdat SULT1A1 ook een rol speelt bij het metabolisme van hormonen (estradiol) kan een verminderde activiteit ook de hormoonbalans beïnvloeden. In dit onderzoek is de variatie rs1042028 getest (Sult1A1*2). T geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde activiteit van SULT1A1. Dit betekent dat mensen met de testuitslag T een lagere snelheid van afbraak van medicijnen en voedingsstoffen hebben dan mensen met de testuitslag C.")
        self.document.add_page_break()
        first_word_bold("SULT1E1 codeert voor het enzym sulfotransferase 1E1. Dit enzym zorgt ervoor, dat bepaalde hormonen genaamd oestrogenen minder actief worden. Het doet dit door een sulfaatgroep aan de oestrogenen vast te maken."
                        "\nWanneer deze sulfaatgroep wordt toegevoegd, worden de oestrogenen minder krachtig en hebben ze minder effect in ons lichaam. Dit is een belangrijke manier waarop ons lichaam de hoeveelheid en de effecten van oestrogenen regelt in verschillende delen van ons lichaam."
                        "\nSULT1E1 speelt dus een belangrijke rol bij het helpen reguleren van oestrogenen in ons lichaam."
                        "\nIn dit onderzoek is de variatie rs3736599 getest. T geeft de aanwezigheid van de variatie aan. Deze variatie wordt geassocieerd met een verhoogde oestrogeenactiviteit. Dit komt omdat de variatie leidt tot een verminderde activiteit en dus minder oestrogenen kan inactiveren. In een studie (observationeel) is aangetoond dat deze variatie bij vrouwen de kans geeft op het ontwikkelen van endometriose. De uitslagen T/C en T/T worden geassocieerd met een verhoogd oestrogeen gehalte."
                        "\nDaarnaast wordt de testuitslagen T/C en T/T in verband gebracht met een hoger risico op bijwerkingen en slechtere werking bij gebruik van antibiotica, antidepressiva en medicijnen bij hoge bloeddruk. Ook bij aanwezigheid van de testuitslag T/C en T/T bij SUT1E1 is er, net zoals bij SULT1A1 kans op meer nervositeit bij gebruik van caffeine, alcoholvergiftiging bij gebruik van ethanol en fructose intolerantie.")
        first_word_bold("TCF7L2 codeert voor de transcriptiefactor 4 (TCF4), die betrokken is bij de regulering van de bloedsuikerspiegel en hoe gevoelig ons lichaam is voor insuline. TCF7L2 heeft invloed op de afgifte van insuline door de alvleesklier en de gevoeligheid van lichaamscellen voor insuline. Variaties in TCF7L2 kunnen leiden tot minder gevoeligheid voor insuline, wat het risico op het ontwikkelen van diabetes verhoogt."
                        "\nBovendien is TCF7L2 betrokken bij de gezondheid van onze darmen. Het heeft invloed op hoe ons darmweefsel functioneert en hoe goed het slijmvlies in onze darmen zijn werk doet als barrière."
                        "\nTCF7L2 speelt ook een rol in ons zenuwstelsel. TCF7L2 is betrokken bij de ontwikkeling en werking van zenuwcellen in ons centrale zenuwstelsel. Onderzoek heeft aangetoond dat veranderingen in TCF7L2 verband kunnen houden met bepaalde neurologische aandoeningen, zoals schizofrenie en bipolaire stoornis."
                        "\nDus, variaties in TCF7L2 kunnen het risico op type 2-diabetes verhogen, mogelijk door de manier waarop insuline wordt gereguleerd. Maar TCF7L2 heeft ook invloed op onze darmgezondheid en ons zenuwstelsel. In dit onderzoek is de variatie rs7903146 getest. T geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde activiteit van TCF7L2. Dit betekent dat mensen met de testuitslag T een lagere gevoeligheid voor insuline hebben dan mensen met de testuitslag C. De testuitslagen C/T en T/T worden geassocieerd met een verhoogd risico op het ontwikkelen van diabetes type 2. Daarnaast is ook aangetoond dat bij een dieet van koolhydraten de kans op het ontwikkelen van diabetes type 2 bij de testuitslagen C/T en T/T aanwezig is.")
        self.document.add_page_break()
        first_word_bold("TMEM165 codeert voor een eiwit genaamd Transmembrane Protein 165.  Dit eiwit heeft vooral te maken met hoe cellen calcium en mangaan verwerken."
                        "\nCalcium speelt een rol in veel belangrijke processen, zoals interactie tussen cellen, spiercontractie en het regelen van de celgroei. Mangaan is een sporenelement, dat belangrijk is voor verschillende enzymreacties in ons lichaam."
                        "\nVariaties in TMEM165 worden geassocieerd met de aandoening CDG-II, waarbij de vorming van glycoproteïnen wordt verstoord. Deze aandoening kan leiden tot een reeks symptomen, waaronder groeivertraging, neurologische problemen en skeletafwijkingen."
                        "\nCongenitale defecten van de glycosylering (CDG) is een groep erfelijke stofwisselingsziekten met verschillende vormen. Deze ziekten beginnen meestal op jonge leeftijd en de symptomen variëren afhankelijk van het specifieke type CDG en de persoon zelf."
                        "\nKinderen met CDG kunnen problemen hebben met eten, wat leidt tot een gebrek aan gewichtstoename en groei. Ze kunnen last hebben van braken en diarree. Daarnaast kunnen ze moeite hebben met bewegen en zich soms zwak voelen. Sommige kinderen hebben problemen met hun evenwicht en het coördineren van bewegingen. Verstandelijke beperkingen komen ook voor bij kinderen met CDG."
                        "\nSommige zichtproblemen, zoals scheelzien of afwijkingen aan het netvlies, kunnen voorkomen. Epilepsie kan zich ook ontwikkelen bij sommige kinderen met CDG. Daarnaast kunnen lever- of hartproblemen optreden, en soms zijn er problemen met bloedingen of bloedstolsels. Ophoping van vocht (oedeem) kan zich voordoen, en sommige kinderen kunnen een ongewone verdeling van lichaamsvet ervaren."
                        "\nIn dit onderzoek is de variatie rs1801260 getest. G geeft de aanwezigheid van de variatie aan. De testtestuitslagen G/A en G/G geven een hoger risico op het ontwikkelen van ADHD. ADHD is een aandoening, die te maken heeft met aandacht en concentratie. Het lijkt erop dat er een verband kan zijn tussen deze genetische variatie en het risico op het ontwikkelen van ADHD.")
        first_word_bold("TNF-α codeert voor een cytokine. Cytokines zijn eiwitten, die fungeren als signaalmoleculen in het immuunsysteem en zijn betrokken bij onder meer ontstekingsreacties. TNF-α wordt geproduceerd door verschillende immuuncellen, zoals macrofagen en T-cellen, als reactie op infecties en weefselschade. Dit helpt om een ontstekingsproces te starten, wat eigenlijk een manier is van ons lichaam om te reageren op onder andere infecties."
                        "\nTNF-α doet meer dan alleen ontstekingen te beginnen. Het helpt ook om immuuncellen te activeren en naar de plaats van de ontsteking te gaan als verdediging tegen ziekteverwekkers. Soms kan TNF-α zelfs bepaalde cellen aanzetten tot geplande celdood, wat kan helpen bij het verwijderen van beschadigde of geïnfecteerde cellen."
                        "\nIn dit onderzoek is de variatie rs1800629 getest. A geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verhoogde productie van TNF-α. Dit betekent dat mensen met de testuitslag A een hoger niveau van TNF-α in hun bloed hebben dan mensen met de testuitslag G."
                        "\nDe testuitslag G/G is de meest voorkomende testuitslag (68%) onder de West-Europese bevolking. Verhoogde niveaus van TNF-α (A/G en A/A) worden in verband gebracht met de kans om reumatoïde artritis, de ziekte van Crohn en psoriasis te ontwikkelen.  Infliximab en Adalimumab remmen van de werking van TNF-α. Bij de uitslagen A/G en A/A kan sprake zijn van een lagere respons op omega-3 vetzuren en een hoger risico op vitamine D tekort.")
        self.document.add_page_break()
        first_word_bold("UCP2 bevat de blauwdruk voor het aanmaken van een eiwit genaamd UnCoupling Protein 2. Dit eiwit heeft een belangrijke taak bij het regelen van onze energiehuishouding en stofwisseling. UCP2 bevindt zich in de mitochondriën, de energiecentrales van onze cellen, en speelt een rol in de productie van ATP, dat is een belangrijke energiebron in onze cellen."
                        "\nUCP2 helpt om onze lichaamstemperatuur te reguleren door extra energie te verbranden, bijvoorbeeld wanneer we het koud hebben (dat noemen we thermogenese). Bovendien heeft UCP2 invloed op hoe onze cellen vetten en glucose verwerken, wat belangrijk is voor het handhaven van een evenwicht in het insulineniveau en de bloedsuikerspiegel."
                        "\nUCP2 kan ook helpen bij het verminderen van oxidatieve stress. Dat is een proces waarbij schadelijke moleculen, zoals Reactive Oxygen Species (ROS), worden verminderd. Deze ROS-moleculen worden vaak bijproducten genoemd, die ontstaan tijdens normale celprocessen, met name in de mitochondriën. Oxidatieve stress treedt op wanneer de balans tussen de productie van ROS en het vermogen van cellen om deze te neutraliseren wordt verstoord. Antioxidanten zoals vitamine C en E kunnen helpen bij het verminderen van oxidatieve stress door deze ROS-moleculen te neutraliseren."
                        "\nInteressant is dat er ook studies zijn die suggereren dat UCP2 een rol kan spelen bij obesitas en type 2-diabetes. Een verminderde expressie van UCP2 zou kunnen leiden tot een verminderd vermogen om vetten te verbranden. Dit kan dan de oorzaak zijn van gewichtstoename.Interessant is dat er ook studies zijn die suggereren dat UCP2 een rol kan spelen bij obesitas en type 2-diabetes. Een verminderde expressie van UCP2 zou kunnen leiden tot een verminderd vermogen om vetten te verbranden. Dit kan dan de oorzaak zijn van gewichtstoename."
                        "In dit onderzoek is specifiek gekeken naar een genetische variatie genaamd rs660339. A geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde expressie van UCP2. Dit betekent dat mensen met de testuitslag A/G en A/A een lagere hoeveelheid UCP2 in hun cellen hebben in vergelijking met mensen met de uitslag G/G.")
        first_word_bold("VDR is verantwoordelijk voor de productie van de vitamine D-receptor. Deze receptor speelt een belangrijke rol bij de manier, waarop ons lichaam vitamine D verwerkt. Denk aan de vitamine D-receptor als een soort 'ontvanger', die zich in verschillende cellen in ons lichaam bevindt, onder andere in onze darmen, botten en nieren."
                        "\nDe vitamine D-receptor helpt het bij het reguleren van de hoeveelheid calcium en fosfaat in ons lichaam, wat essentieel is voor gezonde botten en tanden. Ook speelt de vitamine D-receptor een rol bij het proces van botversterking. Daarnaast is de vitamine D-receptor betrokken bij ons immuunsysteem, dat helpt om infecties te bestrijden."
                        "\nWanneer we vitamine D binnenkrijgen via voedsel of zonlicht, wordt dit omgezet in een actieve vorm genaamd calcitriol. Calcitriol bindt zich met de vitamine D-receptor en helpt ons lichaam om vitamine D op de juiste manier te gebruiken."
                        "\nSommige mensen hebben genetische variaties in VDR. Deze variaties kunnen invloed hebben op hoe hun lichaam reageert op vitamine D. In sommige gevallen kan dit verband houden met gezondheidsproblemen zoals zwakke botten (osteoporose), diabetes type 1 en 2, darmproblemen zoals inflammatoire darmziekten en zelfs multiple sclerose."
                        "\nDit onderzoek heeft specifiek gekeken naar de genetische variatie genaamd rs731236. A geeft de aanwezigheid van de variatie aan. Deze variatie is geassocieerd met een verminderde functie van de vitamine D-receptor. Dit betekent dat mensen met de uitslag A/G en A/A een lagere respons op vitamine D hebben dan mensen met de uitslag G/G. Een lage respons op vitamine D kan risico inhouden op het ontwikkelen van rachitis (een ziekte die leidt tot zwakke botten) en osteoporose (verlies van botmassa). Onder de West-Europese bevolking heeft ongeveer 35% van de mensen als testuitslag A/A. Aanwezigheid van de testuitslag A kan leiden tot een lagere respons op statines en een verhoogd risico op bijwerkingen (constipatie en maagklachten) bij gebruik van calciumsupplementen. Aanvullend darmmicrobioom onderzoek kan worden overwogen bij lage vitamine D niveaus.")

    def save(self):
        """
        Saves the document with a name based on the customer id and the type of document.
        :return:
        """
        document_name = 'NutrinomicsReport' + "_" + self.sample_id + ".docx"
        self.document.save(f"Output\\Reports\\{document_name}")